### PR TITLE
Add testing for Ruby 2.3.0 & 2.4.1, drop support for Ruby 1.9.3

### PR DESCRIPTION
**Pull request by thomasriley**
## Pull Request Checklist

sensu-plugins/sensu-plugins-feature-requests#27

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose
- Add testing for Ruby 2.3.0
- Add testing for Ruby 2.4.1

#### Known Compatablity Issues
- Drop support of Ruby 1.9.3

### CODE REVIEW

**Comment by thomasriley** [comment]
Tests initially failed for this on Ruby 2.0, 2.1 and 2.2.

The clockwork gem has an unbounded dependancy on the activesupport gem. The latest version of activesupport (5.1.2) which is being pulled in by bundle due to this only supports Ruby 2.2.2+

To fix this, I have added a runtime dependancy for activesupport 4.2 so that we support Ruby 2.0+

Is there a different (read: better!) way I could be fixing this @majormoses ?

**Comment by majormoses** [comment]
no, taking a quick look without figuring out what breaks there and working through that the only sane option is to pin on the last working major and revisit when we have the time to dedicate to bumping up these dependencies.

I will merge this after work when I have time to read through all the breaking changes and make releases.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-clockworksms/versions/1.0.0

**Pull request merged**
